FROM python:3.10-slim

WORKDIR /app

# Copiar todo el proyecto
COPY . .

# Instalar dependencias
RUN pip install --no-cache-dir -r api/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
